kind: pipeline
type: docker
volumes:
- name: host
  host:
    path: /var/run/docker.sock
steps:
- name: master_build
  image: node:16-alpine
  pull: always
  commands:
  - npm install
  - npm run build
  when:
    branch:
      include:
      - master
      exclude: []
- name: master_ship
  image: docker:19.03.12
  pull: always
  commands:
  - docker build -t registry.cn-hangzhou.aliyuncs.com/w2wing/cmop-webapp:latest .
  environment:
    GOENV: PROD
  when:
    branch:
      include:
      - master
      exclude: []
  volumes:
  - name: host
    path: /var/run/docker.sock
# - name: master_deploy
#   image: registry.cn-hangzhou.aliyuncs.com/profzone/golang-ondeploy:2.4.3
#   pull: always
#   commands:
#   - eden ci deploy --env=STAGING
#   - eden ci deploy --env=TEST
#   - eden ci deploy --env=DEMO
#   environment:
#     GOENV: PROD
#   when:
#     branch:
#       include:
#       - master
#       exclude: []
#   volumes:
#   - name: temp
#     path: /go
#   - name: host
#     path: /var/run/docker.sock
